import elw130 from "./cards/королева топи.jpg"
import elw116 from "./cards/василиск.jpg"
import elw109 from "./cards/осклизг.jpg"
import elw120 from "./cards/гоблин.jpg"
import elw110 from "./cards/рэккен.jpg"
import elw135 from "./cards/древний огр.jpg"
import elw107 from "./cards/болотник.jpg"
import elw112 from "./cards/хедд.jpg"
import elw136 from "./cards/гидра.jpg"
import elw119 from "./cards/бул'багур.jpg"
import elw27 from "./cards/бон и берроу.jpg"
import elw111 from "./cards/тови.jpg"
import elw10 from "./cards/аколит дзара.jpg"
import elw128 from "./cards/тролль.jpg"
import elw104 from "./cards/махинатор.jpg"
import elw126 from "./cards/вилохвост.jpg"
import elw12 from "./cards/кабаний наездник.jpg"
import elw32 from "./cards/дегаска.jpg"
import elw13 from "./cards/орк.jpg"
import elw4 from "./cards/гиррит.jpg"
import elw125 from "./cards/троллок.jpg"
import elw123 from "./cards/ноками.jpg"
import elw131 from "./cards/медуза горгона.jpg"
import elw62 from "./cards/костедробитель.jpg"
import elw31 from "./cards/ойуун.jpg"
import elw65 from "./cards/ледовый страж.jpg"
import elw20 from "./cards/глорм.jpg"
import elw29 from "./cards/пеший латник.jpg"
import elw121 from "./cards/слизь.jpg"
import elw26 from "./cards/анубисар.jpg"
import elw21 from "./cards/мантикора.jpg"
import elw1 from "./cards/кочевник.jpg"
import elw8 from "./cards/степной волколак.jpg"
import elw18 from "./cards/килсус.jpg"
import elw28 from "./cards/матриарх племени.jpg"
import elw127 from "./cards/исхарская ненасыть.jpg"
import elw117 from "./cards/вайл.jpg"
import elw124 from "./cards/сеятель хвори.jpg"
import elw52 from "./cards/тан ханеранга.jpg"
import elw86 from "./cards/мира.jpg"
import elw82 from "./cards/клаэр.jpg"
import elw48 from "./cards/смотритель горнила.jpg"
import elw5 from "./cards/ост.jpg"
import elw69 from "./cards/атекар.jpg"
import elw43 from "./cards/каменный голем.jpg"
import elw114 from "./cards/грезы архааля.jpg"
import elw7 from "./cards/смотритель стойла.jpg"
import elw19 from "./cards/щитоносец.jpg"
import elw35 from "./cards/гном-поджигатель.jpg"
import elw15 from "./cards/рубаки холверта.jpg"
import elw102 from "./cards/келе.jpg"
import elw25 from "./cards/хронос.jpg"
import elw37 from "./cards/овражный гном.jpg"
import elw40 from "./cards/мразень.jpg"
import elw34 from "./cards/минотавр.jpg"
import elw44 from "./cards/страж чертогов.jpg"
import elw42 from "./cards/знахарь племени.jpg"
import elw169 from "./cards/властелин хаоса.jpg"
import elw185 from "./cards/шакси.jpg"
import elw200 from "./cards/волот.jpg"
import elw96 from "./cards/тергала.jpg"
import elw144 from "./cards/герольд мрака.jpg"
import elw182 from "./cards/матросы аделаиды.jpg"
import elw105 from "./cards/отряд карателей.jpg"
import elw176 from "./cards/наемник.jpg"
import elw103 from "./cards/ижор.jpg"
import elw168 from "./cards/повелитель бездны.jpg"
import elw122 from "./cards/дочь перламутра.jpg"
import elw106 from "./cards/римаанды.jpg"
import elw46 from "./cards/мастер топора.jpg"
import elw188 from "./cards/паладин алламора.jpg"
import elw118 from "./cards/шаман-душегрыз.jpg"
import elw88 from "./cards/резчик идолов.jpg"
import elw38 from "./cards/бешеный маг.jpg"
import elw16 from "./cards/санкторум.jpg"
import elw56 from "./cards/ном.jpg"
import elw9 from "./cards/хозяйка прайда.jpg"
import elw41 from "./cards/айрин.jpg"
import elw49 from "./cards/центурион.jpg"
import elw14 from "./cards/пустынный кондор.jpg"
import elw45 from "./cards/ледовый охотник.jpg"
import elw80 from "./cards/бьерн.jpg"
import elw61 from "./cards/горный великан.jpg"
import elw138 from "./cards/огненный имп.jpg"
import elw64 from "./cards/гобрах.jpg"
import elw150 from "./cards/харон.jpg"
import elw198 from "./cards/варлок.jpg"
import elw53 from "./cards/гном-басаарг.jpg"
import elw173 from "./cards/ведунья ордена.jpg"
import elw159 from "./cards/драккарх.jpg"
import elw170 from "./cards/демон жадности.jpg"
import elw142 from "./cards/суккуб-истязатель.jpg"
import elw97 from "./cards/эльфийский воин.jpg"
import elw183 from "./cards/дозор форрендора.jpg"
import elw73 from "./cards/друид.jpg"
import elw54 from "./cards/искатель тайн.jpg"
import elw75 from "./cards/лесной разбойник.jpg"
import elw167 from "./cards/мерцающий змей.jpg"
import elw100 from "./cards/хобгоблин.jpg"
import elw137 from "./cards/вестник мора.jpg"
import elw36 from "./cards/ледяной змей.jpg"
import elw113 from "./cards/гаррид-лучник.jpg"
import elw33 from "./cards/скелос.jpg"
import elw39 from "./cards/гуль.jpg"
import elw89 from "./cards/грызь.jpg"
import elw184 from "./cards/отшельница.jpg"
import elw30 from "./cards/бронтобей.jpg"
import elw87 from "./cards/фагор.jpg"
import elw66 from "./cards/повелитель молний.jpg"
import elw91 from "./cards/дикий целитель.jpg"
import elw22 from "./cards/орк-бомбардир.jpg"
import elw199 from "./cards/тич.jpg"
import elw146 from "./cards/керсамская знать.jpg"
import elw151 from "./cards/зомби.jpg"
import elw0 from "./cards/дверг.jpg"
import elw164 from "./cards/поганище.jpg"
import elw171 from "./cards/мародер.jpg"
import elw94 from "./cards/король-жрец.jpg"
import elw145 from "./cards/демон зависти.jpg"
import elw133 from "./cards/морок.jpg"
import elw132 from "./cards/двухголовый тролль.jpg"
import elw165 from "./cards/барака.jpg"
import elw195 from "./cards/берсерк.jpg"
import elw179 from "./cards/жжраг.jpg"
import elw108 from "./cards/дети топи.jpg"
import elw115 from "./cards/кровяница.jpg"
import elw166 from "./cards/вурдалак.jpg"
import elw50 from "./cards/хранитель гор.jpg"
import elw181 from "./cards/ловец удачи.jpg"
import elw187 from "./cards/лазутчица.jpg"
import elw92 from "./cards/кобольд.jpg"
import elw79 from "./cards/бегущая по кронам.jpg"
import elw81 from "./cards/вожак сатиров.jpg"
import elw55 from "./cards/борг.jpg"
import elw161 from "./cards/скелетный червь.jpg"
import elw148 from "./cards/сшиватель плоти.jpg"
import elw156 from "./cards/метаморф.jpg"
import elw141 from "./cards/моровой всадник.jpg"
import elw78 from "./cards/эриала.jpg"
import elw98 from "./cards/етун.jpg"
import elw47 from "./cards/ртунх.jpg"
import elw191 from "./cards/ассасин.jpg"
import elw84 from "./cards/камнедрев.jpg"
import elw180 from "./cards/линнет.jpg"
import elw67 from "./cards/гномий король.jpg"
import elw85 from "./cards/лёккен.jpg"
import elw154 from "./cards/мрачная дворянка.jpg"
import elw6 from "./cards/пустотник.jpg"
import elw190 from "./cards/вольный воитель.jpg"
import elw77 from "./cards/паук-пересмешник.jpg"
import elw11 from "./cards/змееглав.jpg"
import elw68 from "./cards/владыка небес.jpg"
import elw76 from "./cards/оури.jpg"
import elw129 from "./cards/ундина.jpg"
import elw71 from "./cards/леший.jpg"
import elw99 from "./cards/серый альв.jpg"
import elw134 from "./cards/уриил.jpg"
import elw192 from "./cards/ревнитель сеггера.jpg"
import elw93 from "./cards/очи кронга.jpg"
import elw95 from "./cards/ловец душ.jpg"
import elw177 from "./cards/следопыт.jpg"
import elw193 from "./cards/арацент.jpg"
import elw147 from "./cards/повелитель мёртвых.jpg"
import elw155 from "./cards/рогатый демон.jpg"
import elw140 from "./cards/ведьма слуа.jpg"
import elw72 from "./cards/фея леса.jpg"
import elw152 from "./cards/пещерник.jpg"
import elw17 from "./cards/арбалетчик.jpg"
import elw153 from "./cards/сайкорон.jpg"
import elw24 from "./cards/посвященный дзара.jpg"
import elw3 from "./cards/волхв.jpg"
import elw160 from "./cards/лилит и эйдерик.jpg"
import elw101 from "./cards/циклоп.jpg"
import elw70 from "./cards/дракс.jpg"
import elw58 from "./cards/молотобоец.jpg"
import elw196 from "./cards/гермет.jpg"
import elw197 from "./cards/эорвал.jpg"
import elw23 from "./cards/риала.jpg"
import elw60 from "./cards/аргвальд.jpg"
import elw74 from "./cards/корпит.jpg"
import elw59 from "./cards/оборотень.jpg"
import elw51 from "./cards/призывающая бурю.jpg"
import elw174 from "./cards/взрывная мэри.jpg"
import elw157 from "./cards/лунная баньши.jpg"
import elw158 from "./cards/уордак.jpg"
import elw194 from "./cards/аристократка.jpg"
import elw186 from "./cards/головорез.jpg"
import elw83 from "./cards/серк.jpg"
import elw175 from "./cards/крондак.jpg"
import elw163 from "./cards/хозяин склепа.jpg"
import elw139 from "./cards/вампир.jpg"
import elw162 from "./cards/тварь.jpg"
import elw172 from "./cards/ведающий запасами.jpg"
import elw57 from "./cards/криомант.jpg"
import elw149 from "./cards/талион.jpg"
import elw143 from "./cards/возница.jpg"
import elw189 from "./cards/воин храма.jpg"
import elw178 from "./cards/алвалинд.jpg"
import elw2 from "./cards/кшар.jpg"
import elw63 from "./cards/рагнар.jpg"
export { elw130, elw116, elw109, elw120, elw110, elw135, elw107, elw112, elw136, elw119, elw27, elw111, elw10, elw128, elw104, elw126, elw12, elw32, elw13, elw4, elw125, elw123, elw131, elw62, elw31, elw65, elw20, elw29, elw121, elw26, elw21, elw1, elw8, elw18, elw28, elw127, elw117, elw124, elw52, elw86, elw82, elw48, elw5, elw69, elw43, elw98, elw7, elw19, elw35, elw15, elw102, elw25, elw37, elw40, elw34, elw44, elw42, elw169, elw185, elw200, elw96, elw144, elw182, elw105, elw176, elw103, elw168, elw122, elw106, elw46, elw188, elw118, elw88, elw38, elw16, elw56, elw9, elw41, elw49, elw14, elw45, elw114, elw61, elw138, elw64, elw150, elw198, elw53, elw173, elw159, elw170, elw142, elw97, elw183, elw73, elw54, elw75, elw167, elw100, elw137, elw36, elw113, elw33, elw39, elw89, elw184, elw30, elw87, elw66, elw91, elw22, elw199, elw146, elw151, elw0, elw164, elw171, elw94, elw145, elw133, elw132, elw165, elw195, elw179, elw108, elw115, elw166, elw50, elw181, elw187, elw92, elw79, elw81, elw55, elw161, elw148, elw156, elw141, elw78, elw80, elw47, elw191, elw84, elw180, elw67, elw85, elw154, elw6, elw190, elw77, elw11, elw68, elw76, elw129, elw71, elw99, elw134, elw192, elw93, elw95, elw177, elw193, elw147, elw155, elw140, elw72, elw152, elw17, elw153, elw24, elw3, elw160, elw101, elw70, elw58, elw196, elw197, elw23, elw60, elw74, elw59, elw51, elw174, elw157, elw158, elw194, elw186, elw83, elw175, elw163, elw139, elw162, elw172, elw57, elw149, elw143, elw189, elw178, elw2, elw63 }