import elw130 from "./cards/королева топи.jpg"
import elw116 from "./cards/василиск.jpg"
import elw109 from "./cards/осклизг.jpg"
import elw120 from "./cards/гоблин.jpg"
import elw110 from "./cards/рэккен.jpg"
import elw135 from "./cards/древний огр.jpg"
import elw107 from "./cards/болотник.jpg"
import elw112 from "./cards/хедд.jpg"
import elw136 from "./cards/гидра.jpg"
import elw119 from "./cards/бул'багур.jpg"
import elw27 from "./cards/бон и берроу.jpg"
import elw111 from "./cards/тови.jpg"
import elw10 from "./cards/аколит дзара.jpg"
import elw128 from "./cards/тролль.jpg"
import elw104 from "./cards/махинатор.jpg"
import elw126 from "./cards/вилохвост.jpg"
import elw12 from "./cards/кабаний наездник.jpg"
import elw32 from "./cards/дегаска.jpg"
import elw13 from "./cards/орк.jpg"
import elw4 from "./cards/гиррит.jpg"
import elw125 from "./cards/троллок.jpg"
import elw123 from "./cards/ноками.jpg"
import elw131 from "./cards/медуза горгона.jpg"
import elw62 from "./cards/костедробитель.jpg"
import elw31 from "./cards/ойуун.jpg"
import elw65 from "./cards/ледовый страж.jpg"
import elw20 from "./cards/глорм.jpg"
import elw29 from "./cards/пеший латник.jpg"
import elw121 from "./cards/слизь.jpg"
import elw26 from "./cards/анубисар.jpg"
import elw21 from "./cards/мантикора.jpg"
import elw1 from "./cards/кочевник.jpg"
import elw8 from "./cards/степной волколак.jpg"
import elw18 from "./cards/килсус.jpg"
import elw28 from "./cards/матриарх племени.jpg"
import elw127 from "./cards/исхарская ненасыть.jpg"
import elw117 from "./cards/вайл.jpg"
import elw124 from "./cards/сеятель хвори.jpg"
import elw52 from "./cards/тан ханеранга.jpg"
import elw86 from "./cards/мира.jpg"
import elw82 from "./cards/клаэр.jpg"
import elw48 from "./cards/смотритель горнила.jpg"
import elw5 from "./cards/ост.jpg"
import elw69 from "./cards/атекар.jpg"
import elw43 from "./cards/каменный голем.jpg"
import elw114 from "./cards/грезы архааля.jpg"
import elw7 from "./cards/смотритель стойла.jpg"
import elw19 from "./cards/щитоносец.jpg"
import elw35 from "./cards/гном-поджигатель.jpg"
import elw15 from "./cards/рубаки холверта.jpg"
import elw102 from "./cards/келе.jpg"
import elw25 from "./cards/хронос.jpg"
import elw37 from "./cards/овражный гном.jpg"
import elw40 from "./cards/мразень.jpg"
import elw34 from "./cards/минотавр.jpg"
import elw44 from "./cards/страж чертогов.jpg"
import elw42 from "./cards/знахарь племени.jpg"
import elw169 from "./cards/властелин хаоса.jpg"
import elw185 from "./cards/шакси.jpg"
import elw200 from "./cards/волот.jpg"
import elw96 from "./cards/тергала.jpg"
import elw144 from "./cards/герольд мрака.jpg"
import elw182 from "./cards/матросы аделаиды.jpg"
import elw105 from "./cards/отряд карателей.jpg"
import elw176 from "./cards/наемник.jpg"
import elw103 from "./cards/ижор.jpg"
import elw168 from "./cards/повелитель бездны.jpg"
import elw122 from "./cards/дочь перламутра.jpg"
import elw106 from "./cards/римаанды.jpg"
import elw46 from "./cards/мастер топора.jpg"
import elw188 from "./cards/паладин алламора.jpg"
import elw118 from "./cards/шаман-душегрыз.jpg"
import elw88 from "./cards/резчик идолов.jpg"
import elw38 from "./cards/бешеный маг.jpg"
import elw16 from "./cards/санкторум.jpg"
import elw56 from "./cards/ном.jpg"
import elw9 from "./cards/хозяйка прайда.jpg"
import elw41 from "./cards/айрин.jpg"
import elw49 from "./cards/центурион.jpg"
import elw14 from "./cards/пустынный кондор.jpg"
import elw45 from "./cards/ледовый охотник.jpg"
import elw80 from "./cards/бьерн.jpg"
import elw61 from "./cards/горный великан.jpg"
import elw138 from "./cards/огненный имп.jpg"
import elw64 from "./cards/гобрах.jpg"
import elw150 from "./cards/харон.jpg"
import elw198 from "./cards/варлок.jpg"
import elw53 from "./cards/гном-басаарг.jpg"
import elw173 from "./cards/ведунья ордена.jpg"
import elw159 from "./cards/драккарх.jpg"
import elw170 from "./cards/демон жадности.jpg"
import elw142 from "./cards/суккуб-истязатель.jpg"
import elw97 from "./cards/эльфийский воин.jpg"
import elw183 from "./cards/дозор форрендора.jpg"
import elw73 from "./cards/друид.jpg"
import elw54 from "./cards/искатель тайн.jpg"
import elw75 from "./cards/лесной разбойник.jpg"
import elw167 from "./cards/мерцающий змей.jpg"
import elw100 from "./cards/хобгоблин.jpg"
import elw137 from "./cards/вестник мора.jpg"
import elw36 from "./cards/ледяной змей.jpg"
import elw113 from "./cards/гаррид-лучник.jpg"
import elw33 from "./cards/скелос.jpg"
import elw39 from "./cards/гуль.jpg"
import elw89 from "./cards/грызь.jpg"
import elw184 from "./cards/отшельница.jpg"
import elw30 from "./cards/бронтобей.jpg"
import elw87 from "./cards/фагор.jpg"
import elw66 from "./cards/повелитель молний.jpg"
import elw91 from "./cards/дикий целитель.jpg"
import elw22 from "./cards/орк-бомбардир.jpg"
import elw199 from "./cards/тич.jpg"
import elw146 from "./cards/керсамская знать.jpg"
import elw151 from "./cards/зомби.jpg"
import elw0 from "./cards/дверг.jpg"
import elw164 from "./cards/поганище.jpg"
import elw171 from "./cards/мародер.jpg"
import elw94 from "./cards/король-жрец.jpg"
import elw145 from "./cards/демон зависти.jpg"
import elw133 from "./cards/морок.jpg"
import elw132 from "./cards/двухголовый тролль.jpg"
import elw165 from "./cards/барака.jpg"
import elw195 from "./cards/берсерк.jpg"
import elw179 from "./cards/жжраг.jpg"
import elw108 from "./cards/дети топи.jpg"
import elw115 from "./cards/кровяница.jpg"
import elw166 from "./cards/вурдалак.jpg"
import elw50 from "./cards/хранитель гор.jpg"
import elw181 from "./cards/ловец удачи.jpg"
import elw187 from "./cards/лазутчица.jpg"
import elw92 from "./cards/кобольд.jpg"
import elw79 from "./cards/бегущая по кронам.jpg"
import elw81 from "./cards/вожак сатиров.jpg"
import elw55 from "./cards/борг.jpg"
import elw161 from "./cards/скелетный червь.jpg"
import elw148 from "./cards/сшиватель плоти.jpg"
import elw156 from "./cards/метаморф.jpg"
import elw141 from "./cards/моровой всадник.jpg"
import elw78 from "./cards/эриала.jpg"
import elw98 from "./cards/етун.jpg"
import elw47 from "./cards/ртунх.jpg"
import elw191 from "./cards/ассасин.jpg"
import elw84 from "./cards/камнедрев.jpg"
import elw180 from "./cards/линнет.jpg"
import elw67 from "./cards/гномий король.jpg"
import elw85 from "./cards/лёккен.jpg"
import elw154 from "./cards/мрачная дворянка.jpg"
import elw6 from "./cards/пустотник.jpg"
import elw190 from "./cards/вольный воитель.jpg"
import elw77 from "./cards/паук-пересмешник.jpg"
import elw11 from "./cards/змееглав.jpg"
import elw68 from "./cards/владыка небес.jpg"
import elw76 from "./cards/оури.jpg"
import elw129 from "./cards/ундина.jpg"
import elw71 from "./cards/леший.jpg"
import elw99 from "./cards/серый альв.jpg"
import elw134 from "./cards/уриил.jpg"
import elw192 from "./cards/ревнитель сеггера.jpg"
import elw93 from "./cards/очи кронга.jpg"
import elw95 from "./cards/ловец душ.jpg"
import elw177 from "./cards/следопыт.jpg"
import elw193 from "./cards/арацент.jpg"
import elw147 from "./cards/повелитель мёртвых.jpg"
import elw155 from "./cards/рогатый демон.jpg"
import elw140 from "./cards/ведьма слуа.jpg"
import elw72 from "./cards/фея леса.jpg"
import elw152 from "./cards/пещерник.jpg"
import elw17 from "./cards/арбалетчик.jpg"
import elw153 from "./cards/сайкорон.jpg"
import elw24 from "./cards/посвященный дзара.jpg"
import elw3 from "./cards/волхв.jpg"
import elw160 from "./cards/лилит и эйдерик.jpg"
import elw101 from "./cards/циклоп.jpg"
import elw70 from "./cards/дракс.jpg"
import elw58 from "./cards/молотобоец.jpg"
import elw196 from "./cards/гермет.jpg"
import elw197 from "./cards/эорвал.jpg"
import elw23 from "./cards/риала.jpg"
import elw60 from "./cards/аргвальд.jpg"
import elw74 from "./cards/корпит.jpg"
import elw59 from "./cards/оборотень.jpg"
import elw51 from "./cards/призывающая бурю.jpg"
import elw174 from "./cards/взрывная мэри.jpg"
import elw157 from "./cards/лунная баньши.jpg"
import elw158 from "./cards/уордак.jpg"
import elw194 from "./cards/аристократка.jpg"
import elw186 from "./cards/головорез.jpg"
import elw83 from "./cards/серк.jpg"
import elw175 from "./cards/крондак.jpg"
import elw163 from "./cards/хозяин склепа.jpg"
import elw139 from "./cards/вампир.jpg"
import elw162 from "./cards/тварь.jpg"
import elw172 from "./cards/ведающий запасами.jpg"
import elw57 from "./cards/криомант.jpg"
import elw149 from "./cards/талион.jpg"
import elw143 from "./cards/возница.jpg"
import elw189 from "./cards/воин храма.jpg"
import elw178 from "./cards/алвалинд.jpg"
import elw2 from "./cards/кшар.jpg"
import elw63 from "./cards/рагнар.jpg"
import din11 from "./cards/пустыня дзара.jpg"
import din24 from "./cards/великая катапульта.jpg"
import din2 from "./cards/кентавр.jpg"
import din21 from "./cards/купец.jpg"
import din19 from "./cards/ясновидящая.jpg"
import din29 from "./cards/орк-арбалетчик.jpg"
import din35 from "./cards/гном-арбалетчик.jpg"
import din20 from "./cards/раптор.jpg"
import din58 from "./cards/глиняный голем.jpg"
import din18 from "./cards/кулхан.jpg"
import din3 from "./cards/орчонок.jpg"
import din15 from "./cards/песчаный пират.jpg"
import din27 from "./cards/пиромант дзара.jpg"
import din42 from "./cards/скальд.jpg"
import din16 from "./cards/пикинёр альхенгарда.jpg"
import din13 from "./cards/витязь адрелиана.jpg"
import din8 from "./cards/кондор-стервятник.jpg"
import din4 from "./cards/разумный вихрь.jpg"
import din10 from "./cards/поури.jpg"
import din6 from "./cards/карлик унд.jpg"
import din9 from "./cards/лихо одноглазое.jpg"
import din59 from "./cards/камень гнева.jpg"
import din62 from "./cards/морозный тюремщик.jpg"
import din74 from "./cards/разведчик эльфов.jpg"
import din30 from "./cards/рыцарь туллена.jpg"
import din71 from "./cards/лепрекон.jpg"
import din33 from "./cards/кест.jpg"
import din39 from "./cards/дух горы.jpg"
import din32 from "./cards/адрелиан.jpg"
import din70 from "./cards/бяка.jpg"
import din73 from "./cards/гигантский орёл.jpg"
import din28 from "./cards/степной варвар.jpg"
import din69 from "./cards/эльм.jpg"
import din56 from "./cards/шипокрыл.jpg"
import din55 from "./cards/скалы лант-мора.jpg"
import din38 from "./cards/гарпунщик.jpg"
import din76 from "./cards/рейнджер.jpg"
import din17 from "./cards/боргак.jpg"
import din77 from "./cards/санитар рощи.jpg"
import din47 from "./cards/ледяной тролль.jpg"
import din78 from "./cards/ламия.jpg"
import din45 from "./cards/астральный двойник.jpg"
import din118 from "./cards/обелиск топей.jpg"
import din86 from "./cards/рузарх.jpg"
import din102 from "./cards/линдвурм.jpg"
import din96 from "./cards/эльфийский арсенал.jpg"
import din109 from "./cards/руины уорлога.jpg"
import din141 from "./cards/скелет.jpg"
import din95 from "./cards/чародейка.jpg"
import din117 from "./cards/джаал.jpg"
import din175 from "./cards/йоро.jpg"
import din100 from "./cards/исса.jpg"
import din110 from "./cards/топи зенды.jpg"
import din49 from "./cards/сердце бурь.jpg"
import din147 from "./cards/берелгал.jpg"
import din146 from "./cards/пустошь тул-багар.jpg"
import din172 from "./cards/аларино.jpg"
import din68 from "./cards/рукан.jpg"
import din173 from "./cards/алтарь хигарта.jpg"
import din171 from "./cards/ури.jpg"
import din114 from "./cards/щупальце кракена.jpg"
import din87 from "./cards/гризли кронга.jpg"
import din105 from "./cards/виверна.jpg"
import din138 from "./cards/выкормыш слуа.jpg"
import din111 from "./cards/торфяной змей.jpg"
import din163 from "./cards/огненный демон.jpg"
import din200 from "./cards/кнеллервирм.jpg"
import din195 from "./cards/горец.jpg"
import din145 from "./cards/проклятый маг.jpg"
import din197 from "./cards/феникс.jpg"
import din115 from "./cards/ядовитый плющ.jpg"
import din193 from "./cards/алетрис.jpg"
import din176 from "./cards/охотник за головами.jpg"
import din160 from "./cards/адепт тьмы.jpg"
import din116 from "./cards/ахти.jpg"
import din84 from "./cards/грост.jpg"
import din104 from "./cards/нервный ург.jpg"
import din174 from "./cards/иркиан.jpg"
import din52 from "./cards/хозяйка лавин.jpg"
import din92 from "./cards/бард святолесья.jpg"
import din155 from "./cards/дзингор.jpg"
import din170 from "./cards/левиафан.jpg"
import din120 from "./cards/хэсодэ.jpg"
import din136 from "./cards/броненосец.jpg"
import din93 from "./cards/орк-птицелов.jpg"
import din119 from "./cards/тифозный вайл.jpg"
import din112 from "./cards/умпи.jpg"
import din63 from "./cards/нага.jpg"
import din125 from "./cards/ведьма.jpg"
import din162 from "./cards/лаэтар.jpg"
import din168 from "./cards/арахнид.jpg"
import din66 from "./cards/хельмир.jpg"
import din186 from "./cards/разящий в ночи.jpg"
import din137 from "./cards/бес.jpg"
import din183 from "./cards/стерегущий добычу.jpg"
import din81 from "./cards/ягуар.jpg"
import din198 from "./cards/хранитель хартии.jpg"
import din185 from "./cards/кьелэрн.jpg"
import din167 from "./cards/раэр.jpg"
import din189 from "./cards/тайник эллиона.jpg"
import din108 from "./cards/призрак зенды.jpg"
import din128 from "./cards/пустоголов.jpg"
import din37 from "./cards/стражница ульфгарда.jpg"
import din148 from "./cards/демонические врата.jpg"
import din153 from "./cards/исчадие.jpg"
import din180 from "./cards/картограф.jpg"
import din99 from "./cards/дикий циклоп.jpg"
import din94 from "./cards/хрумг.jpg"
import din113 from "./cards/шутовка.jpg"
import din133 from "./cards/одинокий призрак.jpg"
import din79 from "./cards/мара.jpg"
import din80 from "./cards/пастух кронга.jpg"
import din199 from "./cards/хигарт.jpg"
import din132 from "./cards/кракен.jpg"
import din157 from "./cards/дракон-зомби.jpg"
import din142 from "./cards/малефик.jpg"
import din144 from "./cards/призрачный рыцарь.jpg"
import din46 from "./cards/гаргулья.jpg"
import din164 from "./cards/королева мёртвых.jpg"
import din149 from "./cards/живущий в тумане.jpg"
import din140 from "./cards/саламандра.jpg"
import din83 from "./cards/гвеор.jpg"
import din166 from "./cards/шарль де лорм.jpg"
import din97 from "./cards/вейде.jpg"
import din75 from "./cards/раэннат.jpg"
import din182 from "./cards/оруженосец.jpg"
import din192 from "./cards/аделаида.jpg"
import din143 from "./cards/могильный демон.jpg"
import din151 from "./cards/надих.jpg"
import din152 from "./cards/скелетная гончая.jpg"
import din159 from "./cards/мертвяцкая бомбарда.jpg"
import din165 from "./cards/темный эльф.jpg"
import din65 from "./cards/торбьерн.jpg"
import din36 from "./cards/лучница снорганга.jpg"
import din48 from "./cards/олаф.jpg"
import din50 from "./cards/сигурд.jpg"
import din54 from "./cards/раннан.jpg"
import din57 from "./cards/валькирия.jpg"
import din72 from "./cards/вепрь святолесья.jpg"
import din89 from "./cards/бурый волк.jpg"
import din101 from "./cards/единорог.jpg"
import din82 from "./cards/борсан.jpg"
import din103 from "./cards/невеста окуня.jpg"
import din124 from "./cards/утопец.jpg"
import din129 from "./cards/слух архааля.jpg"
import din121 from "./cards/информатор.jpg"
import din158 from "./cards/кровавый оракул.jpg"
import din161 from "./cards/всадники слуа.jpg"
import din169 from "./cards/далукар.jpg"
import din179 from "./cards/изувер.jpg"
import din184 from "./cards/ведьмак.jpg"
import din41 from "./cards/ратник крейд-моора.jpg"
import din60 from "./cards/кугхор.jpg"
import din51 from "./cards/черновар.jpg"
import din191 from "./cards/гном-отступник.jpg"
import din106 from "./cards/дымный ууг.jpg"
import din122 from "./cards/ррег.jpg"
import din135 from "./cards/тролль-людоед.jpg"
import din134 from "./cards/король астейрос.jpg"
import din91 from "./cards/эльф-задира.jpg"
import din90 from "./cards/гмурр.jpg"
import din98 from "./cards/тхель-вэнн.jpg"
import din88 from "./cards/часовые кронга.jpg"


import elw27pf from "./cards/бон и берроу пф.jpg"
import elw7pf from "./cards/смотритель стойла пф.jpg"
import elw18pf from "./cards/килсус пф.jpg"
import elw26pf from "./cards/анубисар пф.jpg"
import elw52pf from "./cards/тан ханеранга пф.jpg"
import elw51pf from "./cards/призывающая бурю пф.jpg"
import elw60pf from "./cards/аргвальд пф.jpg"
import elw57pf from "./cards/криомант пф.jpg"
import elw81pf from "./cards/вожак сатиров пф.jpg"
import elw86pf from "./cards/мира пф.jpg"
import elw91pf from "./cards/дикий целитель пф.jpg"
import elw94pf from "./cards/король-жрец пф.jpg"
import elw108pf from "./cards/дети топи пф.jpg"
import elw119pf from "./cards/бул'багур пф.jpg"
import elw123pf from "./cards/ноками пф.jpg"
import elw124pf from "./cards/сеятель хвори пф.jpg"
import elw147pf from "./cards/повелитель мертвых пф.jpg"
import elw155pf from "./cards/рогатый демон пф.jpg"
import elw161pf from "./cards/скелетный червь пф.jpg"
import elw163pf from "./cards/хозяин склепа пф.jpg"
import elw191pf from "./cards/ассасин пф.jpg"
import elw193pf from "./cards/арацент пф.jpg"
import elw34aa from "./cards/минотавр аа.png"
import elw59aa from "./cards/оборотень аа.png"
import elw101aa from "./cards/циклоп аа.jpg"
import elw169aa from "./cards/властелин хаоса аа.jpg"
import elw195aa from "./cards/берсерк аа.jpg"
export { elw50, elw10, elw111, elw60, elw198, elw172, elw138, elw98, elw171, elw80, elw114, elw193, elw152, elw155, din11, din24, din2, din21, din19, elw200, din29, din35, elw191, elw126, elw135, elw117, elw130, elw109, elw131, elw12, elw15, elw105, elw127, elw136, elw27, elw22, elw118, elw30, elw121, elw120, elw3, elw113, elw11, elw116, elw21, elw122, din20, elw134, elw5, din58, elw107, elw119, elw124, elw132, elw123, elw110, elw104, elw115, elw190, elw173, elw186, elw106, elw4, elw24, din18, elw108, elw150, elw163, elw167, elw178, din3, din15, elw164, elw194, din27, din42, din16, elw133, din13, elw158, elw103, elw147, din8, elw175, elw25, din4, elw141, elw182, din10, din6, elw38, elw64, elw7, elw18, elw35, din9, din59, elw184, elw192, elw20, elw189, elw67, elw188, elw29, elw195, elw128, din62, din74, din30, elw174, elw183, din71, din33, din39, elw112, elw185, din32, din70, elw180, din73, din28, din69, din56, din55, din38, elw187, elw199, elw68, elw181, elw179, din76, elw28, elw13, elw129, din17, elw196, elw176, elw197, elw2, din77, elw17, elw125, elw32, elw16, elw61, elw177, din47, din78, elw62, din45, din118, elw74, elw85, din86, din102, din96, elw19, din109, elw58, elw82, elw91, elw47, elw51, din141, elw87, elw93, elw89, elw159, din95, din117, elw156, elw151, din175, din100, elw39, din110, elw56, din49, din147, elw34, elw72, din146, elw48, elw143, din172, din68, din173, elw168, elw37, din171, elw154, din114, elw63, elw8, elw53, din87, din105, din138, elw146, elw95, elw59, elw36, elw148, elw153, din111, din163, din200, din195, din145, din197, din115, elw78, elw45, elw81, din193, elw26, elw57, elw142, elw101, din176, elw149, din160, elw83, elw41, din116, din84, din104, din174, din52, elw169, elw77, din92, elw94, elw44, elw54, din155, elw162, elw43, elw165, elw23, elw52, din170, elw65, elw137, elw161, din120, elw49, din136, elw92, din93, elw157, elw69, din119, din112, elw1, elw70, elw96, elw31, din63, elw79, elw33, elw88, elw160, din125, elw86, elw139, elw55, elw46, din162, elw166, din168, din66, din186, elw145, din137, din183, din81, elw9, din198, din185, elw73, din167, din189, elw99, elw76, elw84, din108, elw40, din128, din37, din148, din153, elw100, din180, din99, din94, din113, din133, elw140, elw75, din79, elw14, elw0, din80, din199, din132, din157, din142, din144, din46, din164, elw66, elw6, elw102, din149, din140, elw71, elw144, elw97, elw170, din83, din166, din97, elw42, din75, din182, din192, din143, din151, din152, din159, din165, din65, din36, din48, din50, din54, din57, din72, din89, din101, din82, din103, din124, din129, din121, din158, din161, din169, din179, din184, din41, din60, din51, din191, din106, din122, din135, din134, din91, din90, din98, din88, elw27pf, elw7pf, elw18pf, elw26pf, elw52pf, elw51pf, elw60pf, elw57pf, elw81pf, elw86pf, elw91pf, elw94pf, elw108pf, elw119pf, elw123pf, elw124pf, elw147pf, elw155pf, elw161pf, elw163pf, elw191pf, elw193pf, elw34aa, elw59aa, elw101aa, elw169aa, elw195aa }