import * as cards from '../assets/images/loader'

export default {
    "хранитель гор": cards.elw50,
    "аколит дзара": cards.elw10,
    "тови": cards.elw111,
    "аргвальд": cards.elw60,
    "варлок": cards.elw198,
    "ведающий запасами": cards.elw172,
    "огненный имп": cards.elw138,
    "арацент": cards.elw193,
    "пещерник": cards.elw152,
    "рогатый демон": cards.elw155,
    "пустыня дзара": cards.din11,
    "великая катапульта": cards.din24,
    "кентавр": cards.din2,
    "купец": cards.din21,
    "ясновидящая": cards.din19,
    "волот": cards.elw200,
    "орк-арбалетчик": cards.din29,
    "гном-арбалетчик": cards.din35,
    "ассасин": cards.elw191,
    "вилохвост": cards.elw126,
    "древний огр": cards.elw135,
    "вайл": cards.elw117,
    "королева топи": cards.elw130,
    "осклизг": cards.elw109,
    "медуза горгона": cards.elw131,
    "кабаний наездник": cards.elw12,
    "рубаки холверта": cards.elw15,
    "отряд карателей": cards.elw105,
    "исхарская ненасыть": cards.elw127,
    "гидра": cards.elw136,
    "бон и берроу": cards.elw27,
    "орк-бомбардир": cards.elw22,
    "шаман-душегрыз": cards.elw118,
    "бронтобей": cards.elw30,
    "слизь": cards.elw121,
    "гоблин": cards.elw120,
    "волхв": cards.elw3,
    "гаррид-лучник": cards.elw113,
    "змееглав": cards.elw11,
    "василиск": cards.elw116,
    "мантикора": cards.elw21,
    "дочь перламутра": cards.elw122,
    "раптор": cards.din20,
    "уриил": cards.elw134,
    "ост": cards.elw5,
    "глиняный голем": cards.din58,
    "болотник": cards.elw107,
    "бул'багур": cards.elw119,
    "сеятель хвори": cards.elw124,
    "двухголовый тролль": cards.elw132,
    "ноками": cards.elw123,
    "рэккен": cards.elw110,
    "грезы архааля": cards.elw114,
    "махинатор": cards.elw104,
    "кровяница": cards.elw115,
    "вольный воитель": cards.elw190,
    "ведунья ордена": cards.elw173,
    "головорез": cards.elw186,
    "римаанды": cards.elw106,
    "гиррит": cards.elw4,
    "посвященный дзара": cards.elw24,
    "кулхан": cards.din18,
    "дети топи": cards.elw108,
    "харон": cards.elw150,
    "хозяин склепа": cards.elw163,
    "мерцающий змей": cards.elw167,
    "алвалинд": cards.elw178,
    "орчонок": cards.din3,
    "песчаный пират": cards.din15,
    "поганище": cards.elw164,
    "аристократка": cards.elw194,
    "пиромант дзара": cards.din27,
    "скальд": cards.din42,
    "пикинер альхенгарда": cards.din16,
    "морок": cards.elw133,
    "витязь адрелиана": cards.din13,
    "уордак": cards.elw158,
    "ижор": cards.elw103,
    "повелитель мертвых": cards.elw147,
    "кондор-стервятник": cards.din8,
    "крондак": cards.elw175,
    "хронос": cards.elw25,
    "разумный вихрь": cards.din4,
    "моровой всадник": cards.elw141,
    "матросы аделаиды": cards.elw182,
    "поури": cards.din10,
    "карлик унд": cards.din6,
    "бешеный маг": cards.elw38,
    "гобрах": cards.elw64,
    "смотритель стойла": cards.elw7,
    "килсус": cards.elw18,
    "гном-поджигатель": cards.elw35,
    "лихо одноглазое": cards.din9,
    "камень гнева": cards.din59,
    "отшельница": cards.elw184,
    "ревнитель сеггера": cards.elw192,
    "мародер": cards.elw171,
    "глорм": cards.elw20,
    "воин храма": cards.elw189,
    "гномий король": cards.elw67,
    "паладин алламора": cards.elw188,
    "пеший латник": cards.elw29,
    "берсерк": cards.elw195,
    "тролль": cards.elw128,
    "морозный тюремщик": cards.din62,
    "разведчик эльфов": cards.din74,
    "рыцарь туллена": cards.din30,
    "взрывная мэри": cards.elw174,
    "дозор форрендора": cards.elw183,
    "лепрекон": cards.din71,
    "кест": cards.din33,
    "дух горы": cards.din39,
    "хедд": cards.elw112,
    "шакси": cards.elw185,
    "адрелиан": cards.din32,
    "бяка": cards.din70,
    "линнет": cards.elw180,
    "гигантский орел": cards.din73,
    "степной варвар": cards.din28,
    "эльм": cards.din69,
    "шипокрыл": cards.din56,
    "скалы лант-мора": cards.din55,
    "гарпунщик": cards.din38,
    "лазутчица": cards.elw187,
    "тич": cards.elw199,
    "владыка небес": cards.elw68,
    "ловец удачи": cards.elw181,
    "жжраг": cards.elw179,
    "рейнджер": cards.din76,
    "матриарх племени": cards.elw28,
    "орк": cards.elw13,
    "ундина": cards.elw129,
    "боргак": cards.din17,
    "гермет": cards.elw196,
    "наемник": cards.elw176,
    "эорвал": cards.elw197,
    "кшар": cards.elw2,
    "санитар рощи": cards.din77,
    "арбалетчик": cards.elw17,
    "троллок": cards.elw125,
    "дегаска": cards.elw32,
    "санкторум": cards.elw16,
    "горный великан": cards.elw61,
    "следопыт": cards.elw177,
    "ледяной тролль": cards.din47,
    "ламия": cards.din78,
    "костедробитель": cards.elw62,
    "астральный двойник": cards.din45,
    "обелиск топей": cards.din118,
    "корпит": cards.elw74,
    "леккен": cards.elw85,
    "рузарх": cards.din86,
    "линдвурм": cards.din102,
    "эльфийский арсенал": cards.din96,
    "щитоносец": cards.elw19,
    "руины уорлога": cards.din109,
    "молотобоец": cards.elw58,
    "клаэр": cards.elw82,
    "дикий целитель": cards.elw91,
    "ртунх": cards.elw47,
    "призывающая бурю": cards.elw51,
    "скелет": cards.din141,
    "фагор": cards.elw87,
    "очи кронга": cards.elw93,
    "грызь": cards.elw89,
    "драккарх": cards.elw159,
    "чародейка": cards.din95,
    "джаал": cards.din117,
    "метаморф": cards.elw156,
    "зомби": cards.elw151,
    "йоро": cards.din175,
    "исса": cards.din100,
    "гуль": cards.elw39,
    "топи зенды": cards.din110,
    "ном": cards.elw56,
    "сердце бурь": cards.din49,
    "берелгал": cards.din147,
    "минотавр": cards.elw34,
    "фея леса": cards.elw72,
    "пустошь тул-багар": cards.din146,
    "смотритель горнила": cards.elw48,
    "возница": cards.elw143,
    "аларино": cards.din172,
    "рукан": cards.din68,
    "алтарь хигарта": cards.din173,
    "повелитель бездны": cards.elw168,
    "овражный гном": cards.elw37,
    "ури": cards.din171,
    "мрачная дворянка": cards.elw154,
    "щупальце кракена": cards.din114,
    "рагнар": cards.elw63,
    "степной волколак": cards.elw8,
    "гном-басаарг": cards.elw53,
    "гризли кронга": cards.din87,
    "виверна": cards.din105,
    "выкормыш слуа": cards.din138,
    "керсамская знать": cards.elw146,
    "ловец душ": cards.elw95,
    "оборотень": cards.elw59,
    "ледяной змей": cards.elw36,
    "сшиватель плоти": cards.elw148,
    "сайкорон": cards.elw153,
    "торфяной змей": cards.din111,
    "огненный демон": cards.din163,
    "кнеллервирм": cards.din200,
    "горец": cards.din195,
    "проклятый маг": cards.din145,
    "феникс": cards.din197,
    "ядовитый плющ": cards.din115,
    "эриала": cards.elw78,
    "ледовый охотник": cards.elw45,
    "вожак сатиров": cards.elw81,
    "алетрис": cards.din193,
    "анубисар": cards.elw26,
    "криомант": cards.elw57,
    "суккуб-истязатель": cards.elw142,
    "циклоп": cards.elw101,
    "охотник за головами": cards.din176,
    "талион": cards.elw149,
    "адепт тьмы": cards.din160,
    "серк": cards.elw83,
    "айрин": cards.elw41,
    "ахти": cards.din116,
    "грост": cards.din84,
    "нервный ург": cards.din104,
    "иркиан": cards.din174,
    "хозяйка лавин": cards.din52,
    "властелин хаоса": cards.elw169,
    "паук-пересмешник": cards.elw77,
    "бард святолесья": cards.din92,
    "король-жрец": cards.elw94,
    "страж чертогов": cards.elw44,
    "искатель тайн": cards.elw54,
    "дзингор": cards.din155,
    "тварь": cards.elw162,
    "каменный голем": cards.elw43,
    "барака": cards.elw165,
    "риала": cards.elw23,
    "тан ханеранга": cards.elw52,
    "левиафан": cards.din170,
    "ледовый страж": cards.elw65,
    "вестник мора": cards.elw137,
    "скелетный червь": cards.elw161,
    "хэсодэ": cards.din120,
    "центурион": cards.elw49,
    "броненосец": cards.din136,
    "кобольд": cards.elw92,
    "орк-птицелов": cards.din93,
    "лунная баньши": cards.elw157,
    "атекар": cards.elw69,
    "тифозный вайл": cards.din119,
    "умпи": cards.din112,
    "кочевник": cards.elw1,
    "дракс": cards.elw70,
    "тергала": cards.elw96,
    "ойуун": cards.elw31,
    "нага": cards.din63,
    "бегущая по кронам": cards.elw79,
    "скелос": cards.elw33,
    "резчик идолов": cards.elw88,
    "лилит и эйдерик": cards.elw160,
    "ведьма": cards.din125,
    "мира": cards.elw86,
    "вампир": cards.elw139,
    "борг": cards.elw55,
    "бьерн": cards.elw80,
    "мастер топора": cards.elw46,
    "лаэтар": cards.din162,
    "вурдалак": cards.elw166,
    "етун": cards.elw98,
    "арахнид": cards.din168,
    "хельмир": cards.din66,
    "разящий в ночи": cards.din186,
    "демон зависти": cards.elw145,
    "бес": cards.din137,
    "стерегущий добычу": cards.din183,
    "ягуар": cards.din81,
    "хозяйка прайда": cards.elw9,
    "хранитель хартии": cards.din198,
    "кьелэрн": cards.din185,
    "друид": cards.elw73,
    "раэр": cards.din167,
    "тайник эллиона": cards.din189,
    "серый альв": cards.elw99,
    "оури": cards.elw76,
    "камнедрев": cards.elw84,
    "призрак зенды": cards.din108,
    "мразень": cards.elw40,
    "пустоголов": cards.din128,
    "стражница ульфгарда": cards.din37,
    "демонические врата": cards.din148,
    "исчадие": cards.din153,
    "хобгоблин": cards.elw100,
    "картограф": cards.din180,
    "дикий циклоп": cards.din99,
    "хрумг": cards.din94,
    "шутовка": cards.din113,
    "одинокий призрак": cards.din133,
    "ведьма слуа": cards.elw140,
    "лесной разбойник": cards.elw75,
    "мара": cards.din79,
    "пустынный кондор": cards.elw14,
    "дверг": cards.elw0,
    "пастух кронга": cards.din80,
    "хигарт": cards.din199,
    "кракен": cards.din132,
    "дракон-зомби": cards.din157,
    "малефик": cards.din142,
    "призрачный рыцарь": cards.din144,
    "гаргулья": cards.din46,
    "королева мертвых": cards.din164,
    "повелитель молний": cards.elw66,
    "пустотник": cards.elw6,
    "келе": cards.elw102,
    "живущий в тумане": cards.din149,
    "саламандра": cards.din140,
    "леший": cards.elw71,
    "герольд мрака": cards.elw144,
    "эльфийский воин": cards.elw97,
    "демон жадности": cards.elw170,
    "гвеор": cards.din83,
    "шарль де лорм": cards.din166,
    "вейде": cards.din97,
    "знахарь племени": cards.elw42,
    "раэннат": cards.din75,
    "оруженосец": cards.din182,
    "аделаида": cards.din192,
    "могильный демон": cards.din143,
    "надих": cards.din151,
    "скелетная гончая": cards.din152,
    "мертвяцкая бомбарда": cards.din159,
    "темный эльф": cards.din165,
    "торбьерн": cards.din65,
    "лучница снорганга": cards.din36,
    "олаф": cards.din48,
    "сигурд": cards.din50,
    "раннан": cards.din54,
    "валькирия": cards.din57,
    "вепрь святолесья": cards.din72,
    "бурый волк": cards.din89,
    "единорог": cards.din101,
    "борсан": cards.din82,
    "невеста окуня": cards.din103,
    "утопец": cards.din124,
    "слух архааля": cards.din129,
    "информатор": cards.din121,
    "кровавый оракул": cards.din158,
    "всадники слуа": cards.din161,
    "далукар": cards.din169,
    "изувер": cards.din179,
    "ведьмак": cards.din184,
    "ратник крейд-моора": cards.din41,
    "кугхор": cards.din60,
    "черновар": cards.din51,
    "гном-отступник": cards.din191,
    "дымный ууг": cards.din106,
    "ррег": cards.din122,
    "тролль-людоед": cards.din135,
    "король астейрос": cards.din134,
    "эльф-задира": cards.din91,
    "гмурр": cards.din90,
    "тхель-вэнн": cards.din98,
    "часовые кронга": cards.din88,
    "зендар": cards.din107,
    "живая стена": cards.din126,
    "древняя черепаха": cards.din130,
    "иринди": cards.din131,
    "сфинкс дзара": cards.din23,
    "могильный жук": cards.din139,
    "землекоп": cards.din178,
    "мумия": cards.din154,
    "гаргант": cards.din64,
    "жрец штормов": cards.din40,
    "рекрутер храма": cards.din187,
    "кешиар": cards.din7,
    "жрица алламора": cards.din85,
    "мастер разума": cards.din194,
    "прорицательница вершин": cards.din53,
    "перевертыш": cards.din156,
    "иглохрюк": cards.din5,
    "стражник туллена": cards.din12,
    "стратег": cards.din22,
    "джилла": cards.din25,
    "маг тор-гарона": cards.din26,
    "трясинщик": cards.din123
} as Record<string, string>

export const pf = {
    "смотритель стойла": cards.elw7pf,
    "килсус": cards.elw18pf,
    "анубисар": cards.elw26pf,
    "тан ханеранга": cards.elw52pf,
    "призывающая бурю": cards.elw51pf,
    "аргвальд": cards.elw60pf,
    "криомант": cards.elw57pf,
    "вожак сатиров": cards.elw81pf,
    "мира": cards.elw86pf,
    "дикий целитель": cards.elw91pf,
    "король-жрец": cards.elw94pf,
    "дети топи": cards.elw108pf,
    "бул'багур": cards.elw119pf,
    "ноками": cards.elw123pf,
    "сеятель хвори": cards.elw124pf,
    "повелитель мертвых": cards.elw147pf,
    "рогатый демон": cards.elw155pf,
    "скелетный червь": cards.elw161pf,
    "хозяин склепа": cards.elw163pf,
    "ассасин": cards.elw191pf,
    "арацент": cards.elw193pf,
    "эльм": cards.din69pf,
    "скелет": cards.din141pf,
    "нервный ург": cards.din104pf,
    "щупальце кракена": cards.din114pf,
} as Record<string, string>

export const aa = {
    "минотавр": cards.elw34aa,
    "оборотень": cards.elw59aa,
    "циклоп": cards.elw101aa,
    "властелин хаоса": cards.elw169aa,
    "берсерк": cards.elw195aa,
    "гарпунщик": cards.din38aa,
    "оруженосец": cards.din182aa,
    "умпи": cards.din112aa
} as Record<string, string>
// 'королева топи': './src/assets/images/cards/королева топи.jpg',
//     'василиск': './src/assets/images/cards/василиск.jpg',
//     'осклизг': './src/assets/images/cards/осклизг.jpg',
//     'гоблин': './src/assets/images/cards/гоблин.jpg',
//     'рэккен': './src/assets/images/cards/рэккен.jpg',
//     'древний огр': './src/assets/images/cards/древний огр.jpg',
//     'болотник': './src/assets/images/cards/болотник.jpg',
//     'хедд': './src/assets/images/cards/хедд.jpg',
//     'гидра': './src/assets/images/cards/гидра.jpg',
//     "бул'багур": "./src/assets/images/cards/бул'багур.jpg",
//     'бон и берроу': './src/assets/images/cards/бон и берроу.jpg',
//     'тови': './src/assets/images/cards/тови.jpg',
//     'аколит дзара': './src/assets/images/cards/аколит дзара.jpg',
//     'тролль': './src/assets/images/cards/тролль.jpg',
//     'махинатор': './src/assets/images/cards/махинатор.jpg',
//     'вилохвост': './src/assets/images/cards/вилохвост.jpg',
//     'кабаний наездник': './src/assets/images/cards/кабаний наездник.jpg',
//     'дегаска': './src/assets/images/cards/дегаска.jpg',
//     'орк': './src/assets/images/cards/орк.jpg',
//     'гиррит': './src/assets/images/cards/гиррит.jpg',
//     'троллок': './src/assets/images/cards/троллок.jpg',
//     'ноками': './src/assets/images/cards/ноками.jpg',
//     'медуза горгона': './src/assets/images/cards/медуза горгона.jpg',
//     'костедробитель': './src/assets/images/cards/костедробитель.jpg',
//     'ойуун': './src/assets/images/cards/ойуун.jpg',
//     'ледовый страж': './src/assets/images/cards/ледовый страж.jpg',
//     'глорм': './src/assets/images/cards/глорм.jpg',
//     'пеший латник': './src/assets/images/cards/пеший латник.jpg',
//     'слизь': './src/assets/images/cards/слизь.jpg',
//     'анубисар': './src/assets/images/cards/анубисар.jpg',
//     'мантикора': './src/assets/images/cards/мантикора.jpg',
//     'кочевник': './src/assets/images/cards/кочевник.jpg',
//     'степной волколак': './src/assets/images/cards/степной волколак.jpg',
//     'килсус': './src/assets/images/cards/килсус.jpg',
//     'матриарх племени': './src/assets/images/cards/матриарх племени.jpg',
//     'исхарская ненасыть': './src/assets/images/cards/исхарская ненасыть.jpg',
//     'вайл': './src/assets/images/cards/вайл.jpg',
//     'сеятель хвори': './src/assets/images/cards/сеятель хвори.jpg',
//     'тан ханеранга': './src/assets/images/cards/тан ханеранга.jpg',
//     'мира': './src/assets/images/cards/мира.jpg',
//     'клаэр': './src/assets/images/cards/клаэр.jpg',
//     'смотритель горнила': './src/assets/images/cards/смотритель горнила.jpg',
//     'ост': './src/assets/images/cards/ост.jpg',
//     'атекар': './src/assets/images/cards/атекар.jpg',
//     'каменный голем': './src/assets/images/cards/каменный голем.jpg',
//     'грезы архааля': './src/assets/images/cards/грезы архааля.jpg',
//     'смотритель стойла': './src/assets/images/cards/смотритель стойла.jpg',
//     'щитоносец': './src/assets/images/cards/щитоносец.jpg',
//     'гном-поджигатель': './src/assets/images/cards/гном-поджигатель.jpg',
//     'рубаки холверта': './src/assets/images/cards/рубаки холверта.jpg',
//     'келе': './src/assets/images/cards/келе.jpg',
//     'хронос': './src/assets/images/cards/хронос.jpg',
//     'овражный гном': './src/assets/images/cards/овражный гном.jpg',
//     'мразень': './src/assets/images/cards/мразень.jpg',
//     'минотавр': './src/assets/images/cards/минотавр.jpg',
//     'страж чертогов': './src/assets/images/cards/страж чертогов.jpg',
//     'знахарь племени': './src/assets/images/cards/знахарь племени.jpg',
//     'властелин хаоса': './src/assets/images/cards/властелин хаоса.jpg',
//     'шакси': './src/assets/images/cards/шакси.jpg',
//     'волот': './src/assets/images/cards/волот.jpg',
//     'тергала': './src/assets/images/cards/тергала.jpg',
//     'герольд мрака': './src/assets/images/cards/герольд мрака.jpg',
//     'матросы аделаиды': './src/assets/images/cards/матросы аделаиды.jpg',
//     'отряд карателей': './src/assets/images/cards/отряд карателей.jpg',
//     'наемник': './src/assets/images/cards/наемник.jpg',
//     'ижор': './src/assets/images/cards/ижор.jpg',
//     'повелитель бездны': './src/assets/images/cards/повелитель бездны.jpg',
//     'дочь перламутра': './src/assets/images/cards/дочь перламутра.jpg',
//     'римаанды': './src/assets/images/cards/римаанды.jpg',
//     'мастер топора': './src/assets/images/cards/мастер топора.jpg',
//     'паладин алламора': './src/assets/images/cards/паладин алламора.jpg',
//     'шаман-душегрыз': './src/assets/images/cards/шаман-душегрыз.jpg',
//     'резчик идолов': './src/assets/images/cards/резчик идолов.jpg',
//     'бешеный маг': './src/assets/images/cards/бешеный маг.jpg',
//     'санкторум': './src/assets/images/cards/санкторум.jpg',
//     'ном': './src/assets/images/cards/ном.jpg',
//     'хозяйка прайда': './src/assets/images/cards/хозяйка прайда.jpg',
//     'айрин': './src/assets/images/cards/айрин.jpg',
//     'центурион': './src/assets/images/cards/центурион.jpg',
//     'пустынный кондор': './src/assets/images/cards/пустынный кондор.jpg',
//     'ледовый охотник': './src/assets/images/cards/ледовый охотник.jpg',
//     'бьерн': './src/assets/images/cards/бьерн.jpg',
//     'горный великан': './src/assets/images/cards/горный великан.jpg',
//     'огненный имп': './src/assets/images/cards/огненный имп.jpg',
//     'гобрах': './src/assets/images/cards/гобрах.jpg',
//     'харон': './src/assets/images/cards/харон.jpg',
//     'варлок': './src/assets/images/cards/варлок.jpg',
//     'гном-басаарг': './src/assets/images/cards/гном-басаарг.jpg',
//     'ведунья ордена': './src/assets/images/cards/ведунья ордена.jpg',
//     'драккарх': './src/assets/images/cards/драккарх.jpg',
//     'демон жадности': './src/assets/images/cards/демон жадности.jpg',
//     'суккуб-истязатель': './src/assets/images/cards/суккуб-истязатель.jpg',
//     'эльфийский воин': './src/assets/images/cards/эльфийский воин.jpg',
//     'дозор форрендора': './src/assets/images/cards/дозор форрендора.jpg',
//     'друид': './src/assets/images/cards/друид.jpg',
//     'искатель тайн': './src/assets/images/cards/искатель тайн.jpg',
//     'лесной разбойник': './src/assets/images/cards/лесной разбойник.jpg',
//     'мерцающий змей': './src/assets/images/cards/мерцающий змей.jpg',
//     'хобгоблин': './src/assets/images/cards/хобгоблин.jpg',
//     'вестник мора': './src/assets/images/cards/вестник мора.jpg',
//     'ледяной змей': './src/assets/images/cards/ледяной змей.jpg',
//     'гаррид-лучник': './src/assets/images/cards/гаррид-лучник.jpg',
//     'скелос': './src/assets/images/cards/скелос.jpg',
//     'гуль': './src/assets/images/cards/гуль.jpg',
//     'грызь': './src/assets/images/cards/грызь.jpg',
//     'отшельница': './src/assets/images/cards/отшельница.jpg',
//     'бронтобей': './src/assets/images/cards/бронтобей.jpg',
//     'фагор': './src/assets/images/cards/фагор.jpg',
//     'повелитель молний': './src/assets/images/cards/повелитель молний.jpg',
//     'дикий целитель': './src/assets/images/cards/дикий целитель.jpg',
//     'орк-бомбардир': './src/assets/images/cards/орк-бомбардир.jpg',
//     'тич': './src/assets/images/cards/тич.jpg',
//     'керсамская знать': './src/assets/images/cards/керсамская знать.jpg',
//     'зомби': './src/assets/images/cards/зомби.jpg',
//     'дверг': './src/assets/images/cards/дверг.jpg',
//     'поганище': './src/assets/images/cards/поганище.jpg',
//     'мародер': './src/assets/images/cards/мародер.jpg',
//     'король-жрец': './src/assets/images/cards/король-жрец.jpg',
//     'демон зависти': './src/assets/images/cards/демон зависти.jpg',
//     'морок': './src/assets/images/cards/морок.jpg',
//     'двухголовый тролль': './src/assets/images/cards/двухголовый тролль.jpg',
//     'барака': './src/assets/images/cards/барака.jpg',
//     'берсерк': './src/assets/images/cards/берсерк.jpg',
//     'жжраг': './src/assets/images/cards/жжраг.jpg',
//     'дети топи': './src/assets/images/cards/дети топи.jpg',
//     'кровяница': './src/assets/images/cards/кровяница.jpg',
//     'вурдалак': './src/assets/images/cards/вурдалак.jpg',
//     'хранитель гор': './src/assets/images/cards/хранитель гор.jpg',
//     'ловец удачи': './src/assets/images/cards/ловец удачи.jpg',
//     'лазутчица': './src/assets/images/cards/лазутчица.jpg',
//     'кобольд': './src/assets/images/cards/кобольд.jpg',
//     'бегущая по кронам': './src/assets/images/cards/бегущая по кронам.jpg',
//     'вожак сатиров': './src/assets/images/cards/вожак сатиров.jpg',
//     'борг': './src/assets/images/cards/борг.jpg',
//     'скелетный червь': './src/assets/images/cards/скелетный червь.jpg',
//     'сшиватель плоти': './src/assets/images/cards/сшиватель плоти.jpg',
//     'метаморф': './src/assets/images/cards/метаморф.jpg',
//     'моровой всадник': './src/assets/images/cards/моровой всадник.jpg',
//     'эриала': './src/assets/images/cards/эриала.jpg',
//     'етун': './src/assets/images/cards/етун.jpg',
//     'ртунх': './src/assets/images/cards/ртунх.jpg',
//     'ассасин': './src/assets/images/cards/ассасин.jpg',
//     'камнедрев': './src/assets/images/cards/камнедрев.jpg',
//     'линнет': './src/assets/images/cards/линнет.jpg',
//     'гномий король': './src/assets/images/cards/гномий король.jpg',
//     'леккен': './src/assets/images/cards/лёккен.jpg',
//     'мрачная дворянка': './src/assets/images/cards/мрачная дворянка.jpg',
//     'пустотник': './src/assets/images/cards/пустотник.jpg',
//     'вольный воитель': './src/assets/images/cards/вольный воитель.jpg',
//     'паук-пересмешник': './src/assets/images/cards/паук-пересмешник.jpg',
//     'змееглав': './src/assets/images/cards/змееглав.jpg',
//     'владыка небес': './src/assets/images/cards/владыка небес.jpg',
//     'оури': './src/assets/images/cards/оури.jpg',
//     'ундина': './src/assets/images/cards/ундина.jpg',
//     'леший': './src/assets/images/cards/леший.jpg',
//     'серый альв': './src/assets/images/cards/серый альв.jpg',
//     'уриил': './src/assets/images/cards/уриил.jpg',
//     'ревнитель сеггера': './src/assets/images/cards/ревнитель сеггера.jpg',
//     'очи кронга': './src/assets/images/cards/очи кронга.jpg',
//     'ловец душ': './src/assets/images/cards/ловец душ.jpg',
//     'следопыт': './src/assets/images/cards/следопыт.jpg',
//     'арацент': './src/assets/images/cards/арацент.jpg',
//     'повелитель мертвых': './src/assets/images/cards/повелитель мёртвых.jpg',
//     'рогатый демон': './src/assets/images/cards/рогатый демон.jpg',
//     'ведьма слуа': './src/assets/images/cards/ведьма слуа.jpg',
//     'фея леса': './src/assets/images/cards/фея леса.jpg',
//     'пещерник': './src/assets/images/cards/пещерник.jpg',
//     'арбалетчик': './src/assets/images/cards/арбалетчик.jpg',
//     'сайкорон': './src/assets/images/cards/сайкорон.jpg',
//     'посвященный дзара': './src/assets/images/cards/посвященный дзара.jpg',
//     'волхв': './src/assets/images/cards/волхв.jpg',
//     'лилит и эйдерик': './src/assets/images/cards/лилит и эйдерик.jpg',
//     'циклоп': './src/assets/images/cards/циклоп.jpg',
//     'дракс': './src/assets/images/cards/дракс.jpg',
//     'молотобоец': './src/assets/images/cards/молотобоец.jpg',
//     'гермет': './src/assets/images/cards/гермет.jpg',
//     'эорвал': './src/assets/images/cards/эорвал.jpg',
//     'риала': './src/assets/images/cards/риала.jpg',
//     'аргвальд': './src/assets/images/cards/аргвальд.jpg',
//     'корпит': './src/assets/images/cards/корпит.jpg',
//     'оборотень': './src/assets/images/cards/оборотень.jpg',
//     'призывающая бурю': './src/assets/images/cards/призывающая бурю.jpg',
//     'взрывная мэри': './src/assets/images/cards/взрывная мэри.jpg',
//     'лунная баньши': './src/assets/images/cards/лунная баньши.jpg',
//     'уордак': './src/assets/images/cards/уордак.jpg',
//     'аристократка': './src/assets/images/cards/аристократка.jpg',
//     'головорез': './src/assets/images/cards/головорез.jpg',
//     'серк': './src/assets/images/cards/серк.jpg',
//     'крондак': './src/assets/images/cards/крондак.jpg',
//     'хозяин склепа': './src/assets/images/cards/хозяин склепа.jpg',
//     'вампир': './src/assets/images/cards/вампир.jpg',
//     'тварь': './src/assets/images/cards/тварь.jpg',
//     'ведающий запасами': './src/assets/images/cards/ведающий запасами.jpg',
//     'криомант': './src/assets/images/cards/криомант.jpg',
//     'талион': './src/assets/images/cards/талион.jpg',
//     'возница': './src/assets/images/cards/возница.jpg',
//     'воин храма': './src/assets/images/cards/воин храма.jpg',
//     'алвалинд': './src/assets/images/cards/алвалинд.jpg',
//     'кшар': './src/assets/images/cards/кшар.jpg',
//     'рагнар': './src/assets/images/cards/рагнар.jpg',