
export default {
    'королева топи': './src/assets/images/cards/королева топи.jpg',
    'василиск': './src/assets/images/cards/василиск.jpg',
    'осклизг': './src/assets/images/cards/осклизг.jpg',
    'гоблин': './src/assets/images/cards/гоблин.jpg',
    'рэккен': './src/assets/images/cards/рэккен.jpg',
    'древний огр': './src/assets/images/cards/древний огр.jpg',
    'болотник': './src/assets/images/cards/болотник.jpg',
    'хедд': './src/assets/images/cards/хедд.jpg',
    'гидра': './src/assets/images/cards/гидра.jpg',
    "бул'багур": "./src/assets/images/cards/бул'багур.jpg",
    'бон и берроу': './src/assets/images/cards/бон и берроу.jpg',
    'тови': './src/assets/images/cards/тови.jpg',
    'аколит дзара': './src/assets/images/cards/аколит дзара.jpg',
    'тролль': './src/assets/images/cards/тролль.jpg',
    'махинатор': './src/assets/images/cards/махинатор.jpg',
    'вилохвост': './src/assets/images/cards/вилохвост.jpg',
    'кабаний наездник': './src/assets/images/cards/кабаний наездник.jpg',
    'дегаска': './src/assets/images/cards/дегаска.jpg',
    'орк': './src/assets/images/cards/орк.jpg',
    'гиррит': './src/assets/images/cards/гиррит.jpg',
    'троллок': './src/assets/images/cards/троллок.jpg',
    'ноками': './src/assets/images/cards/ноками.jpg',
    'медуза горгона': './src/assets/images/cards/медуза горгона.jpg',
    'костедробитель': './src/assets/images/cards/костедробитель.jpg',
    'ойуун': './src/assets/images/cards/ойуун.jpg',
    'ледовый страж': './src/assets/images/cards/ледовый страж.jpg',
    'глорм': './src/assets/images/cards/глорм.jpg',
    'пеший латник': './src/assets/images/cards/пеший латник.jpg',
    'слизь': './src/assets/images/cards/слизь.jpg',
    'анубисар': './src/assets/images/cards/анубисар.jpg',
    'мантикора': './src/assets/images/cards/мантикора.jpg',
    'кочевник': './src/assets/images/cards/кочевник.jpg',
    'степной волколак': './src/assets/images/cards/степной волколак.jpg',
    'килсус': './src/assets/images/cards/килсус.jpg',
    'матриарх племени': './src/assets/images/cards/матриарх племени.jpg',
    'исхарская ненасыть': './src/assets/images/cards/исхарская ненасыть.jpg',
    'вайл': './src/assets/images/cards/вайл.jpg',
    'сеятель хвори': './src/assets/images/cards/сеятель хвори.jpg',
    'тан ханеранга': './src/assets/images/cards/тан ханеранга.jpg',
    'мира': './src/assets/images/cards/мира.jpg',
    'клаэр': './src/assets/images/cards/клаэр.jpg',
    'смотритель горнила': './src/assets/images/cards/смотритель горнила.jpg',
    'ост': './src/assets/images/cards/ост.jpg',
    'атекар': './src/assets/images/cards/атекар.jpg',
    'каменный голем': './src/assets/images/cards/каменный голем.jpg',
    'грезы архааля': './src/assets/images/cards/грезы архааля.jpg',
    'смотритель стойла': './src/assets/images/cards/смотритель стойла.jpg',
    'щитоносец': './src/assets/images/cards/щитоносец.jpg',
    'гном-поджигатель': './src/assets/images/cards/гном-поджигатель.jpg',
    'рубаки холверта': './src/assets/images/cards/рубаки холверта.jpg',
    'келе': './src/assets/images/cards/келе.jpg',
    'хронос': './src/assets/images/cards/хронос.jpg',
    'овражный гном': './src/assets/images/cards/овражный гном.jpg',
    'мразень': './src/assets/images/cards/мразень.jpg',
    'минотавр': './src/assets/images/cards/минотавр.jpg',
    'страж чертогов': './src/assets/images/cards/страж чертогов.jpg',
    'знахарь племени': './src/assets/images/cards/знахарь племени.jpg',
    'властелин хаоса': './src/assets/images/cards/властелин хаоса.jpg',
    'шакси': './src/assets/images/cards/шакси.jpg',
    'волот': './src/assets/images/cards/волот.jpg',
    'тергала': './src/assets/images/cards/тергала.jpg',
    'герольд мрака': './src/assets/images/cards/герольд мрака.jpg',
    'матросы аделаиды': './src/assets/images/cards/матросы аделаиды.jpg',
    'отряд карателей': './src/assets/images/cards/отряд карателей.jpg',
    'наемник': './src/assets/images/cards/наемник.jpg',
    'ижор': './src/assets/images/cards/ижор.jpg',
    'повелитель бездны': './src/assets/images/cards/повелитель бездны.jpg',
    'дочь перламутра': './src/assets/images/cards/дочь перламутра.jpg',
    'римаанды': './src/assets/images/cards/римаанды.jpg',
    'мастер топора': './src/assets/images/cards/мастер топора.jpg',
    'паладин алламора': './src/assets/images/cards/паладин алламора.jpg',
    'шаман-душегрыз': './src/assets/images/cards/шаман-душегрыз.jpg',
    'резчик идолов': './src/assets/images/cards/резчик идолов.jpg',
    'бешеный маг': './src/assets/images/cards/бешеный маг.jpg',
    'санкторум': './src/assets/images/cards/санкторум.jpg',
    'ном': './src/assets/images/cards/ном.jpg',
    'хозяйка прайда': './src/assets/images/cards/хозяйка прайда.jpg',
    'айрин': './src/assets/images/cards/айрин.jpg',
    'центурион': './src/assets/images/cards/центурион.jpg',
    'пустынный кондор': './src/assets/images/cards/пустынный кондор.jpg',
    'ледовый охотник': './src/assets/images/cards/ледовый охотник.jpg',
    'бьерн': './src/assets/images/cards/бьерн.jpg',
    'горный великан': './src/assets/images/cards/горный великан.jpg',
    'огненный имп': './src/assets/images/cards/огненный имп.jpg',
    'гобрах': './src/assets/images/cards/гобрах.jpg',
    'харон': './src/assets/images/cards/харон.jpg',
    'варлок': './src/assets/images/cards/варлок.jpg',
    'гном-басаарг': './src/assets/images/cards/гном-басаарг.jpg',
    'ведунья ордена': './src/assets/images/cards/ведунья ордена.jpg',
    'драккарх': './src/assets/images/cards/драккарх.jpg',
    'демон жадности': './src/assets/images/cards/демон жадности.jpg',
    'суккуб-истязатель': './src/assets/images/cards/суккуб-истязатель.jpg',
    'эльфийский воин': './src/assets/images/cards/эльфийский воин.jpg',
    'дозор форрендора': './src/assets/images/cards/дозор форрендора.jpg',
    'друид': './src/assets/images/cards/друид.jpg',
    'искатель тайн': './src/assets/images/cards/искатель тайн.jpg',
    'лесной разбойник': './src/assets/images/cards/лесной разбойник.jpg',
    'мерцающий змей': './src/assets/images/cards/мерцающий змей.jpg',
    'хобгоблин': './src/assets/images/cards/хобгоблин.jpg',
    'вестник мора': './src/assets/images/cards/вестник мора.jpg',
    'ледяной змей': './src/assets/images/cards/ледяной змей.jpg',
    'гаррид-лучник': './src/assets/images/cards/гаррид-лучник.jpg',
    'скелос': './src/assets/images/cards/скелос.jpg',
    'гуль': './src/assets/images/cards/гуль.jpg',
    'грызь': './src/assets/images/cards/грызь.jpg',
    'отшельница': './src/assets/images/cards/отшельница.jpg',
    'бронтобей': './src/assets/images/cards/бронтобей.jpg',
    'фагор': './src/assets/images/cards/фагор.jpg',
    'повелитель молний': './src/assets/images/cards/повелитель молний.jpg',
    'дикий целитель': './src/assets/images/cards/дикий целитель.jpg',
    'орк-бомбардир': './src/assets/images/cards/орк-бомбардир.jpg',
    'тич': './src/assets/images/cards/тич.jpg',
    'керсамская знать': './src/assets/images/cards/керсамская знать.jpg',
    'зомби': './src/assets/images/cards/зомби.jpg',
    'дверг': './src/assets/images/cards/дверг.jpg',
    'поганище': './src/assets/images/cards/поганище.jpg',
    'мародер': './src/assets/images/cards/мародер.jpg',
    'король-жрец': './src/assets/images/cards/король-жрец.jpg',
    'демон зависти': './src/assets/images/cards/демон зависти.jpg',
    'морок': './src/assets/images/cards/морок.jpg',
    'двухголовый тролль': './src/assets/images/cards/двухголовый тролль.jpg',
    'барака': './src/assets/images/cards/барака.jpg',
    'берсерк': './src/assets/images/cards/берсерк.jpg',
    'жжраг': './src/assets/images/cards/жжраг.jpg',
    'дети топи': './src/assets/images/cards/дети топи.jpg',
    'кровяница': './src/assets/images/cards/кровяница.jpg',
    'вурдалак': './src/assets/images/cards/вурдалак.jpg',
    'хранитель гор': './src/assets/images/cards/хранитель гор.jpg',
    'ловец удачи': './src/assets/images/cards/ловец удачи.jpg',
    'лазутчица': './src/assets/images/cards/лазутчица.jpg',
    'кобольд': './src/assets/images/cards/кобольд.jpg',
    'бегущая по кронам': './src/assets/images/cards/бегущая по кронам.jpg',
    'вожак сатиров': './src/assets/images/cards/вожак сатиров.jpg',
    'борг': './src/assets/images/cards/борг.jpg',
    'скелетный червь': './src/assets/images/cards/скелетный червь.jpg',
    'сшиватель плоти': './src/assets/images/cards/сшиватель плоти.jpg',
    'метаморф': './src/assets/images/cards/метаморф.jpg',
    'моровой всадник': './src/assets/images/cards/моровой всадник.jpg',
    'эриала': './src/assets/images/cards/эриала.jpg',
    'етун': './src/assets/images/cards/етун.jpg',
    'ртунх': './src/assets/images/cards/ртунх.jpg',
    'ассасин': './src/assets/images/cards/ассасин.jpg',
    'камнедрев': './src/assets/images/cards/камнедрев.jpg',
    'линнет': './src/assets/images/cards/линнет.jpg',
    'гномий король': './src/assets/images/cards/гномий король.jpg',
    'лёккен': './src/assets/images/cards/лёккен.jpg',
    'мрачная дворянка': './src/assets/images/cards/мрачная дворянка.jpg',
    'пустотник': './src/assets/images/cards/пустотник.jpg',
    'вольный воитель': './src/assets/images/cards/вольный воитель.jpg',
    'паук-пересмешник': './src/assets/images/cards/паук-пересмешник.jpg',
    'змееглав': './src/assets/images/cards/змееглав.jpg',
    'владыка небес': './src/assets/images/cards/владыка небес.jpg',
    'оури': './src/assets/images/cards/оури.jpg',
    'ундина': './src/assets/images/cards/ундина.jpg',
    'леший': './src/assets/images/cards/леший.jpg',
    'серый альв': './src/assets/images/cards/серый альв.jpg',
    'уриил': './src/assets/images/cards/уриил.jpg',
    'ревнитель сеггера': './src/assets/images/cards/ревнитель сеггера.jpg',
    'очи кронга': './src/assets/images/cards/очи кронга.jpg',
    'ловец душ': './src/assets/images/cards/ловец душ.jpg',
    'следопыт': './src/assets/images/cards/следопыт.jpg',
    'арацент': './src/assets/images/cards/арацент.jpg',
    'повелитель мёртвых': './src/assets/images/cards/повелитель мёртвых.jpg',
    'рогатый демон': './src/assets/images/cards/рогатый демон.jpg',
    'ведьма слуа': './src/assets/images/cards/ведьма слуа.jpg',
    'фея леса': './src/assets/images/cards/фея леса.jpg',
    'пещерник': './src/assets/images/cards/пещерник.jpg',
    'арбалетчик': './src/assets/images/cards/арбалетчик.jpg',
    'сайкорон': './src/assets/images/cards/сайкорон.jpg',
    'посвященный дзара': './src/assets/images/cards/посвященный дзара.jpg',
    'волхв': './src/assets/images/cards/волхв.jpg',
    'лилит и эйдерик': './src/assets/images/cards/лилит и эйдерик.jpg',
    'циклоп': './src/assets/images/cards/циклоп.jpg',
    'дракс': './src/assets/images/cards/дракс.jpg',
    'молотобоец': './src/assets/images/cards/молотобоец.jpg',
    'гермет': './src/assets/images/cards/гермет.jpg',
    'эорвал': './src/assets/images/cards/эорвал.jpg',
    'риала': './src/assets/images/cards/риала.jpg',
    'аргвальд': './src/assets/images/cards/аргвальд.jpg',
    'корпит': './src/assets/images/cards/корпит.jpg',
    'оборотень': './src/assets/images/cards/оборотень.jpg',
    'призывающая бурю': './src/assets/images/cards/призывающая бурю.jpg',
    'взрывная мэри': './src/assets/images/cards/взрывная мэри.jpg',
    'лунная баньши': './src/assets/images/cards/лунная баньши.jpg',
    'уордак': './src/assets/images/cards/уордак.jpg',
    'аристократка': './src/assets/images/cards/аристократка.jpg',
    'головорез': './src/assets/images/cards/головорез.jpg',
    'серк': './src/assets/images/cards/серк.jpg',
    'крондак': './src/assets/images/cards/крондак.jpg',
    'хозяин склепа': './src/assets/images/cards/хозяин склепа.jpg',
    'вампир': './src/assets/images/cards/вампир.jpg',
    'тварь': './src/assets/images/cards/тварь.jpg',
    'ведающий запасами': './src/assets/images/cards/ведающий запасами.jpg',
    'криомант': './src/assets/images/cards/криомант.jpg',
    'талион': './src/assets/images/cards/талион.jpg',
    'возница': './src/assets/images/cards/возница.jpg',
    'воин храма': './src/assets/images/cards/воин храма.jpg',
    'алвалинд': './src/assets/images/cards/алвалинд.jpg',
    'кшар': './src/assets/images/cards/кшар.jpg',
    'рагнар': './src/assets/images/cards/рагнар.jpg',
} as Record<string, string>


    // "вайл": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20117-page-00001.jpg",
    // "болотник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20107-page-00001.jpg",
    // "вилохвост": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20126-page-00001.jpg",
    // "двухголовый тролль": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20132-page-00001.jpg",
    // "бул'багур": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20119-page-00001.jpg",
    // "василиск": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20116-page-00001.jpg",
    // "гаррид-лучник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20113-page-00001.jpg",
    // "гидра": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20136-page-00001.jpg",
    // "гоблин": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20120-page-00001.jpg",
    // "грезы архааля": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20114-page-00001.jpg",
    // "дети топи": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20108-page-00001.jpg",
    // "дочь перламутра": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20122-page-00001.jpg",
    // "древний огр": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20135-page-00001.jpg",
    // "ижор": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20103-page-00001.jpg",
    // "исхарская ненасыть": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20127-page-00001.jpg",
    // "королева топи": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20130-page-00001.jpg",
    // "кровяница": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20115-page-00001.jpg",
    // "махинатор": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20104-page-00001.jpg",
    // "медуза горгона": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20131-page-00001.jpg",
    // "морок": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20133-page-00001.jpg",
    // "ноками": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20123-page-00001.jpg",
    // "осклизг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20109-page-00001.jpg",
    // "отряд карателей": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20105-page-00001.jpg",
    // "римаанды": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20106-page-00001.jpg",
    // "рэккен": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20110-page-00001.jpg",
    // "сеятель хвори": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20124-page-00001.jpg",
    // "слизь": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20121-page-00001.jpg",
    // "тови": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20111-page-00001.jpg",
    // "троллок": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20125-page-00001.jpg",
    // "тролль": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20128-page-00001.jpg",
    // "ундина": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20129-page-00001.jpg",
    // "уриил": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20134-page-00001.jpg",
    // "хедд": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20112-page-00001.jpg",
    // "шаман-душегрыз": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20118-page-00001.jpg",
    // "аколит дзара": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2010-page-00001.jpg",
    // "анубисар": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2026-page-00001.jpg",
    // "арбалетчик": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2017-page-00001.jpg",
    // "бон и берроу": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2027-page-00001.jpg",
    // "бронтобей": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2030-page-00001.jpg",
    // "волхв": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%203-page-00001.jpg",
    // "гиррит": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%204-page-00001.jpg",
    // "глорм": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2020-page-00001.jpg",
    // "дегаска": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2032-page-00001.jpg",
    // "змееглав": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2011-page-00001.jpg",
    // "кабаний наездник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2012-page-00001.jpg",
    // "килсус": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2018-page-00001.jpg",
    // "кочевник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%201-page-00001.jpg",
    // "кшар": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%202-page-00001.jpg",
    // "мантикора": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2021-page-00001.jpg",
    // "матриарх племени": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2028-page-00001.jpg",
    // "минотавр": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2034-page-00001.jpg",
    // "ойуун": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2031-page-00001.jpg",
    // "орк": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2013-page-00001.jpg",
    // "орк-бомбардир": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2022-page-00001.jpg",
    // "ост": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%205-page-00001.jpg",
    // "пеший латник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2029-page-00001.jpg",
    // "посвященный дзара": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2024-page-00001.jpg",
    // "пустотник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%206-page-00001.jpg",
    // "пустынный кондор": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2014-page-00001.jpg",
    // "риала": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2023-page-00001.jpg",
    // "рубаки холверта": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2015-page-00001.jpg",
    // "санкторум": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2016-page-00001.jpg",
    // "скелос": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2033-page-00001.jpg",
    // "смотритель стойла": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%207-page-00001.jpg",
    // "степной волколак": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%208-page-00001.jpg",
    // "хозяйка прайда": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%209-page-00001.jpg",
    // "хронос": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2025-page-00001.jpg",
    // "щитоносец": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2019-page-00001.jpg",
    // "айрин": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2041-page-00001.jpg",
    // "аргвальд": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2060-page-00001.jpg",
    // "бешеный маг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2038-page-00001.jpg",
    // "борг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2055-page-00001.jpg",
    // "владыка небес": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2068-page-00001.jpg",
    // "гном-басаарг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2053-page-00001.jpg",
    // "гном-поджигатель": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2035-page-00001.jpg",
    // "гномий король": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2067-page-00001.jpg",
    // "гобрах": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2064-page-00001.jpg",
    // "горный великан": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2061-page-00001.jpg",
    // "гуль": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2039-page-00001.jpg",
    // "знахарь племени": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2042-page-00001.jpg",
    // "искатель тайн": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2054-page-00001.jpg",
    // "каменный голем": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2043-page-00001.jpg",
    // "костедробитель": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2062-page-00001.jpg",
    // "криомант": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2057-page-00001.jpg",
    // "ледовый охотник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2045-page-00001.jpg",
    // "ледовый страж": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2065-page-00001.jpg",
    // "ледяной змей": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2036-page-00001.jpg",
    // "мастер топора": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2046-page-00001.jpg",
    // "молотобоец": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2058-page-00001.jpg",
    // "мразень": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2040-page-00001.jpg",
    // "ном": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2056-page-00001.jpg",
    // "оборотень": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2059-page-00001.jpg",
    // "овражный гном": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2037-page-00001.jpg",
    // "повелитель молний": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2066-page-00001.jpg",
    // "призывающая бурю": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2051-page-00001.jpg",
    // "рагнар": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2063-page-00001.jpg",
    // "ртунх": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2047-page-00001.jpg",
    // "смотритель горнила": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2048-page-00001.jpg",
    // "страж чертогов": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2044-page-00001.jpg",
    // "тан ханеранга": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2052-page-00001.jpg",
    // "хранитель гор": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2050-page-00001.jpg",
    // "центурион": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2049-page-00001.jpg",
    // "атекар": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2069-page-00001.jpg",
    // "бегущая по кронам": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2079-page-00001.jpg",
    // "бьерн": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2080-page-00001.jpg",
    // "вожак сатиров": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2081-page-00001.jpg",
    // "грызь": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2089-page-00001.jpg",
    // "дверг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2090-page-00001.jpg",
    // "дикий целитель": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2091-page-00001.jpg",
    // "дракс": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2070-page-00001.jpg",
    // "друид": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2073-page-00001.jpg",
    // "етун": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2098-page-00001.jpg",
    // "камнедрев": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2084-page-00001.jpg",
    // "келе": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20102-page-00001.jpg",
    // "клаэр": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2082-page-00001.jpg",
    // "кобольд": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2092-page-00001.jpg",
    // "король-жрец": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2094-page-00001.jpg",
    // "корпит": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2074-page-00001.jpg",
    // "лёккен": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2085-page-00001.jpg",
    // "лесной разбойник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2075-page-00001.jpg",
    // "леший": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2071-page-00001.jpg",
    // "ловец душ": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2095-page-00001.jpg",
    // "мира": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2086-page-00001.jpg",
    // "оури": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2076-page-00001.jpg",
    // "очи кронга": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2093-page-00001.jpg",
    // "паук-пересмешник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2077-page-00001.jpg",
    // "резчик идолов": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2088-page-00001.jpg",
    // "серк": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2083-page-00001.jpg",
    // "серый альв": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2099-page-00001.jpg",
    // "тергала": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2096-page-00001.jpg",
    // "фагор": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2087-page-00001.jpg",
    // "фея леса": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2072-page-00001.jpg",
    // "хобгоблин": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20100-page-00001.jpg",
    // "циклоп": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20101-page-00001.jpg",
    // "эльфийский воин": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2097-page-00001.jpg",
    // "эриала": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%2078-page-00001.jpg",
    // "барака": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20165-page-00001.jpg",
    // "вампир": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20139-page-00001.jpg",
    // "ведьма слуа": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20140-page-00001.jpg",
    // "вестник мора": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20137-page-00001.jpg",
    // "властелин хаоса": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20169-page-00001.jpg",
    // "возница": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20143-page-00001.jpg",
    // "вурдалак": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20166-page-00001.jpg",
    // "герольд мрака": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20144-page-00001.jpg",
    // "демон жадности": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20170-page-00001.jpg",
    // "демон зависти": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20145-page-00001.jpg",
    // "драккарх": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20159-page-00001.jpg",
    // "зомби": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20151-page-00001.jpg",
    // "керсамская знать": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20146-page-00001.jpg",
    // "лилит и эйдерик": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20160-page-00001.jpg",
    // "лунная баньши": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20157-page-00001.jpg",
    // "мерцающий змей": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20167-page-00001.jpg",
    // "метаморф": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20156-page-00001.jpg",
    // "моровой всадник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20141-page-00001.jpg",
    // "мрачная дворянка": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20154-page-00001.jpg",
    // "огненный имп": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20138-page-00001.jpg",
    // "пещерник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20152-page-00001.jpg",
    // "повелитель бездны": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20168-page-00001.jpg",
    // "повелитель мёртвых": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20147-page-00001.jpg",
    // "поганище": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20164-page-00001.jpg",
    // "рогатый демон": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20155-page-00001.jpg",
    // "сайкорон": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20153-page-00001.jpg",
    // "скелетный червь": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20161-page-00001.jpg",
    // "суккуб-истязатель": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20142-page-00001.jpg",
    // "сшиватель плоти": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20148-page-00001.jpg",
    // "талион": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20149-page-00001.jpg",
    // "тварь": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20162-page-00001.jpg",
    // "уордак": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20158-page-00001.jpg",
    // "харон": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20150-page-00001.jpg",
    // "хозяин склепа": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Berserk_VS_all_card%20163-page-00001.jpg",
    // "алвалинд": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(178).jpg",
    // "арацент": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(193).jpg",
    // "аристократка": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(194).jpg",
    // "ассасин": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(191).jpg",
    // "берсерк": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(195).jpg",
    // "варлок": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(198).jpg",
    // "ведающий запасами": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(172).jpg",
    // "ведунья ордена": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(173).jpg",
    // "взрывная мэри": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(174).jpg",
    // "воин храма": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(189).jpg",
    // "волот": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(200).jpg",
    // "вольный воитель": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(190).jpg",
    // "гермет": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(196).jpg",
    // "головорез": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(186).jpg",
    // "дозор форрендора": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(183).jpg",
    // "жжраг": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(179).jpg",
    // "крондак": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(175).jpg",
    // "лазутчица": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(187).jpg",
    // "линнет": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(180).jpg",
    // "ловец удачи": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(181).jpg",
    // "мародер": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(171).jpg",
    // "матросы аделаиды": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(182).jpg",
    // "наемник": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(176).jpg",
    // "отшельница": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(184).jpg",
    // "паладин алламора": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(188).jpg",
    // "ревнитель сеггера": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(192).jpg",
    // "следопыт": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(177).jpg",
    // "тич": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(199).jpg",
    // "шакси": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(185).jpg",
    // "эорвал": "https://berserk.ru/image/data/00_Berserk/01_Война%20стихий/Card%20(197).jpg"